"""Agent Card specification and utilities.

Every agent generated by AGENT-LAB is provisioned with an Agent Card:
a cryptographically-signed identity document (JWT for Centralized, DID/VC for Distributed).
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from agent_lab.models.agents import ReasoningType, SecurityClearance


class AgentCardSpec(BaseModel):
    """Full Agent Card specification for identity and access control.

    Contents:
    - Agent ID & Domain
    - Security Clearance
    - Reasoning Type (deterministic or llm-based)
    - Capabilities

    When Agent A calls Agent B via gRPC, the Agent Card is passed in the
    gRPC metadata header. Agent B evaluates the card against its local
    policy engine before accepting the payload.
    """

    agent_id: str = Field(..., description="Unique agent identifier (e.g. hr-worker-01)")
    domain: str = Field(default="", description="Business domain (e.g. HR, Finance)")
    clearance: SecurityClearance = SecurityClearance.LOW_PUBLIC
    reasoning: ReasoningType = ReasoningType.DETERMINISTIC
    capabilities: list[str] = Field(default_factory=list)
    can_delegate_to: list[str] = Field(default_factory=list)

    def is_high_security(self) -> bool:
        """High-security tasks strictly require deterministic reasoning."""
        return (
            self.clearance
            in (SecurityClearance.CONFIDENTIAL, SecurityClearance.TOP_SECRET)
            and self.reasoning == ReasoningType.DETERMINISTIC
        )

    def can_access(self, target_clearance: SecurityClearance) -> bool:
        """Check if this agent's clearance meets or exceeds the target."""
        order = list(SecurityClearance)
        return order.index(self.clearance) >= order.index(target_clearance)
