"""Native Python code generation adapter for deterministic Simple Operators.

Generates lightweight, framework-free Python code for agents where
LLM hallucination risks are unacceptable (e.g. file readers, API callers, DB queries).
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from agent_lab.generators.base import GeneratorAdapter
from agent_lab.generators.registry import GeneratorRegistry

if TYPE_CHECKING:
    from agent_lab.models.asl import AgenticArchitecture


class NativePythonGenerator(GeneratorAdapter):
    """Generates deterministic Python code without LLM framework dependencies."""

    name = "native-python"

    def generate(self, spec: AgenticArchitecture, output_dir: Path) -> list[Path]:
        generated: list[Path] = []
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate native tool stubs
        for tool in spec.spec.layers.tools:
            if tool.framework.value == "native":
                path = output_dir / "tools" / f"{tool.name}.py"
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(self._render_native_tool(tool, spec))
                generated.append(path)

        for agent in spec.spec.layers.execution:
            if agent.type.value == "simple_operator" and agent.language == "python":
                path = output_dir / "workers" / f"{agent.name}.py"
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(self._render_simple_operator(agent, spec))
                generated.append(path)

        return generated

    def generate_dockerfile(self, spec: AgenticArchitecture, output_dir: Path) -> Path:
        path = output_dir / "Dockerfile"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY . .\n"
            'CMD ["python", "-m", "worker"]\n'
        )
        return path

    def generate_k8s_manifests(self, spec: AgenticArchitecture, output_dir: Path) -> list[Path]:
        # Minimal deployment per simple operator
        manifests_dir = output_dir / "k8s"
        manifests_dir.mkdir(parents=True, exist_ok=True)
        generated: list[Path] = []

        for agent in spec.spec.layers.execution:
            if agent.type.value == "simple_operator" and agent.language == "python":
                path = manifests_dir / f"{agent.name}-deployment.yaml"
                path.write_text(
                    f"apiVersion: apps/v1\n"
                    f"kind: Deployment\n"
                    f"metadata:\n"
                    f"  name: {agent.name}\n"
                    f"spec:\n"
                    f"  replicas: 1\n"
                    f"  selector:\n"
                    f"    matchLabels:\n"
                    f"      app: {agent.name}\n"
                    f"  template:\n"
                    f"    metadata:\n"
                    f"      labels:\n"
                    f"        app: {agent.name}\n"
                    f"    spec:\n"
                    f"      containers:\n"
                    f"      - name: {agent.name}\n"
                    f'        image: "{spec.metadata.name}/{agent.name}:latest"\n'
                )
                generated.append(path)

        return generated

    @staticmethod
    def _render_native_tool(tool: object, spec: AgenticArchitecture) -> str:
        name = getattr(tool, "name", "tool")
        desc = getattr(tool, "description", "")
        class_name = name.replace("_", " ").title().replace(" ", "")
        return (
            f'"""Native Tool: {name} — {desc}"""\n'
            f"\n"
            f"# Auto-generated by AGENT-LAB — {spec.metadata.name}\n"
            f"# Framework: native (no LLM dependency)\n"
            f"\n"
            f"\n"
            f"class {class_name}Tool:\n"
            f'    """{desc}"""\n'
            f"\n"
            f"    def invoke(self, **kwargs) -> dict:\n"
            f'        """Execute the tool."""\n'
            f"        raise NotImplementedError\n"
        )

    @staticmethod
    def _render_simple_operator(agent: object, spec: AgenticArchitecture) -> str:
        name = getattr(agent, "name", "worker")
        return (
            f'"""Deterministic Simple Operator: {name}"""\n'
            f"\n"
            f"# Auto-generated by AGENT-LAB — {spec.metadata.name}\n"
            f"# Type: Simple Operator (deterministic, zero hallucination risk)\n"
            f"\n"
            f"\n"
            f"class {name.replace('_', ' ').title().replace(' ', '')}Operator:\n"
            f'    """Deterministic worker — no LLM dependency."""\n'
            f"\n"
            f"    def execute(self, payload: dict) -> dict:\n"
            f'        """Execute the deterministic operation."""\n'
            f"        raise NotImplementedError\n"
        )


GeneratorRegistry.register("native-python", NativePythonGenerator)
